/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.5.0-247
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v2';


// Services

export interface IbanDef {
    checksum: (iban: string, callParams: CallParams<'iban'>) => string | Promise<string>;
    client: (iban: string, callParams: CallParams<'iban'>) => string | Promise<string>;
    createIndirect: (options: { identifier: string; institution: string; }, callParams: CallParams<'options'>) => string | Promise<string>;
    fromAddress: (address: string, callParams: CallParams<'address'>) => string | Promise<string>;
    fromBban: (bbanAddress: string, callParams: CallParams<'bbanAddress'>) => string | Promise<string>;
    institution: (iban: string, callParams: CallParams<'iban'>) => string | Promise<string>;
    isDirect: (iban: string, callParams: CallParams<'iban'>) => boolean | Promise<boolean>;
    isIndirect: (iban: string, callParams: CallParams<'iban'>) => boolean | Promise<boolean>;
    isValid: (iban: string, callParams: CallParams<'iban'>) => boolean | Promise<boolean>;
    toAddress: (iban: string, callParams: CallParams<'iban'>) => string | Promise<string>;
    toIban: (address: string, callParams: CallParams<'address'>) => string | Promise<string>;
    toString: (iban: string, callParams: CallParams<'iban'>) => string | Promise<string>;
}
export function registerIban(service: IbanDef): void;
export function registerIban(serviceId: string, service: IbanDef): void;
export function registerIban(peer: FluencePeer, service: IbanDef): void;
export function registerIban(peer: FluencePeer, serviceId: string, service: IbanDef): void;
       

export function registerIban(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "Iban",
    "functions" : [
        {
            "functionName" : "checksum",
            "argDefs" : [
                {
                    "name" : "iban",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "client",
            "argDefs" : [
                {
                    "name" : "iban",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "createIndirect",
            "argDefs" : [
                {
                    "name" : "options",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "fromAddress",
            "argDefs" : [
                {
                    "name" : "address",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "fromBban",
            "argDefs" : [
                {
                    "name" : "bbanAddress",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "institution",
            "argDefs" : [
                {
                    "name" : "iban",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "isDirect",
            "argDefs" : [
                {
                    "name" : "iban",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "isIndirect",
            "argDefs" : [
                {
                    "name" : "iban",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "isValid",
            "argDefs" : [
                {
                    "name" : "iban",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "toAddress",
            "argDefs" : [
                {
                    "name" : "iban",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "toIban",
            "argDefs" : [
                {
                    "name" : "address",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "toString",
            "argDefs" : [
                {
                    "name" : "iban",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        }
    ]
}
    );
}
      
// Functions

